"""add user_branch_created_by

Revision ID: 070424378497
Revises: b9c859ac4295
Create Date: 2025-08-10 01:07:07.763259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '070424378497'
down_revision: Union[str, Sequence[str], None] = 'b9c859ac4295'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branch', sa.Column('created_by_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'branch', 'user', ['created_by_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'branch', type_='foreignkey')
    op.drop_column('branch', 'created_by_id')
    # ### end Alembic commands ###
