"""add user_branch_link table

Revision ID: 09e8b5dd93c2
Revises: 4c52d0524c7b
Create Date: 2025-08-08 06:36:09.163005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09e8b5dd93c2'
down_revision: Union[str, Sequence[str], None] = '4c52d0524c7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branch',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_branch_id'), 'branch', ['id'], unique=False)
    op.create_index(op.f('ix_branch_name'), 'branch', ['name'], unique=False)
    op.create_table('user_branch_link',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'branch_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_branch_link')
    op.drop_index(op.f('ix_branch_name'), table_name='branch')
    op.drop_index(op.f('ix_branch_id'), table_name='branch')
    op.drop_table('branch')
    # ### end Alembic commands ###
