"""must_change_password

Revision ID: 4c52d0524c7b
Revises: 1f5ab3dbe95e
Create Date: 2025-08-07 05:09:17.938355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4c52d0524c7b'
down_revision: Union[str, Sequence[str], None] = '1f5ab3dbe95e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('password_reset_token', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_constraint(op.f('password_reset_token_token_key'), 'password_reset_token', type_='unique')
    op.create_index(op.f('ix_password_reset_token_expires_at'), 'password_reset_token', ['expires_at'], unique=False)
    op.add_column(
        "user",
        sa.Column("must_change_password", sa.Boolean(), nullable=False, server_default=sa.false())
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'must_change_password')
    op.drop_index(op.f('ix_password_reset_token_expires_at'), table_name='password_reset_token')
    op.create_unique_constraint(op.f('password_reset_token_token_key'), 'password_reset_token', ['token'], postgresql_nulls_not_distinct=False)
    op.alter_column('password_reset_token', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    # ### end Alembic commands ###
